# Generated by Django 3.1.1 on 2020-11-25 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_animal', models.CharField(max_length=50, verbose_name='Nombre animal')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('telefono', models.CharField(max_length=9, verbose_name='Numero de telefono')),
                ('servicio', models.CharField(choices=[('Consulta', 'Consulta, vacunas, desparasitación o chip'), ('Examen', 'Exámenes de laboratorio'), ('Imagenología', 'Imagenología (Ecografía, Radiografía, otros)'), ('Peluqueria', 'Peluqueria, baño, corte de uñas'), ('Esterilización', 'Esterilización'), ('Otro', 'Otro (Puedes añadir informacion extra)')], max_length=150, verbose_name='Servicio')),
                ('fecha_atencion', models.DateField(verbose_name='Fecha de atencion')),
                ('comentario', models.CharField(max_length=250, verbose_name='Informacion extra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
