# Generated by Django 3.1.1 on 2020-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_auto_20201125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.CharField(choices=[('Por defecto', 'Elige una opcion'), ('Consulta', 'Consulta, vacunas, desparasitación o chip'), ('Examen', 'Exámenes de laboratorio'), ('Imagenología', 'Imagenología (Ecografía, Radiografía, otros)'), ('Peluqueria', 'Peluqueria, baño, corte de uñas'), ('Esterilización', 'Esterilización'), ('Otro', 'Otro (Puedes añadir informacion extra)')], default='Por defecto', max_length=150, verbose_name='Servicio'),
        ),
    ]
