# Generated by Django 3.1.1 on 2020-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0006_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('id_animal_propietario', models.IntegerField(verbose_name='Id propietario')),
                ('id_animal_veterinario', models.IntegerField(verbose_name='Id veterinario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre animal')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('sexo', models.CharField(choices=[('Por defecto', 'Elige una opcion'), ('Hembra', 'H'), ('Macho', 'M')], default='Por defecto', max_length=20, verbose_name='Sexo')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado')),
            ],
        ),
    ]
