# Generated by Django 3.1.1 on 2020-12-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0010_auto_20201214_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='foto',
        ),
    ]
